[package]
name = "docker-clone"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
nix = { version = "0.27", features = ["fs","process", "sched", "mount","hostname"] }
anyhow = "1.0"
